name: deploy-eks-rocketseat

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment name'
        required: true
        default: 'dev'
      ENV_VERSION:
        description: 'Environment version'
        required: true
        default: 'v1'

jobs:
  deploy-eks-rocketseat:
    env:
      NAME: k8s-rocketseat
      AWS_REGION: us-east-1
      ENV: ${{ github.event.inputs.ENV }}
      ENV_VERSION: ${{ github.event.inputs.ENV_VERSION }}
      CLUSTER_REGION: us-east-1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure-crentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_EKS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_EKS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: deploy
      run: chmod +x ./devops/scripts/deploy.sh && ./devops/scripts/deploy.sh